#!/usr/bin/env python3
"""
QC trends — turn weeks of QC findings into concrete prompt improvements.

A single week's QC report tells you which episode was weak. Across many weeks
the SAME complaints repeat, and those recurring patterns are the ones worth
fixing at the prompt level. This agent reads the accumulated QC reports, asks
Gemini to cluster the findings into recurring patterns, and proposes a specific
edit to TONE_GUIDANCE for each one.

It deliberately does NOT edit the prompt. NotebookLM cannot learn between
episodes and its output is non-deterministic, so an autonomous
prompt-optimizing loop would chase noise. This produces a proposal the user
approves (or rejects); a human applies the change.

    python scripts/qc_trends.py                 # last 8 weeks
    python scripts/qc_trends.py --weeks 12
    python scripts/qc_trends.py --min-count 3   # only patterns seen 3+ times

Writes summaries/qc-trends.md (repo root of summaries/, not a date folder,
since it spans weeks) and pushes an ntfy summary.

Needs GEMINI_API_KEY. Skips itself cleanly without it.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

DEFAULT_MODEL = os.environ.get("QC_MODEL", "gemini-2.5-flash")


# ── Harvest findings from the weekly QC reports ───────────────────────────────
def _report_dates(weeks: int) -> list[str]:
    root = REPO_ROOT / "summaries"
    if not root.exists():
        return []
    dates = []
    for sub in root.iterdir():
        if not sub.is_dir() or not (sub / "qc-report.md").exists():
            continue
        try:
            datetime.strptime(sub.name, "%Y-%m-%d")
        except ValueError:
            continue
        dates.append(sub.name)
    return sorted(dates, reverse=True)[:weeks]


def _parse_report(date_str: str) -> dict:
    """Pull the per-episode scores and the free-text findings out of one
    weekly qc-report.md. The report is generated by qc_review.py, so its shape
    is stable: a scores table, then '| חומרה | מה נאמר... |' discrepancy tables
    and bulleted 'מאמרים שדולגו' / 'הערות איכות' lists."""
    p = REPO_ROOT / "summaries" / date_str / "qc-report.md"
    text = p.read_text(encoding="utf-8")
    out = {"date": date_str, "scores": [], "discrepancies": [], "notes": [],
           "missed": []}

    for line in text.splitlines():
        s = line.strip()
        # Scores table: | <icon> title | acc | cov | flu | verdict |
        m = re.match(r"^\|\s*[✅🟡🔴⚪]\s*(.+?)\s*\|\s*(\d)\s*\|\s*(\d)\s*\|\s*(\d)\s*\|\s*(\w+)\s*\|$", s)
        if m:
            out["scores"].append({
                "episode": m.group(1), "accuracy": int(m.group(2)),
                "coverage": int(m.group(3)), "fluency": int(m.group(4)),
                "verdict": m.group(5),
            })
            continue
        # Discrepancy rows: | ⚠️/▪️ | said | source |
        m = re.match(r"^\|\s*(⚠️|▪️)\s*\|(.+?)\|(.+?)\|$", s)
        if m:
            out["discrepancies"].append({
                "severity": "high" if m.group(1) == "⚠️" else "low",
                "said": m.group(2).strip(), "source": m.group(3).strip(),
            })
            continue
        if s.startswith("- "):
            out["notes"].append(s[2:].strip())
    return out


def harvest(weeks: int) -> dict:
    dates = _report_dates(weeks)
    reports = [_parse_report(d) for d in dates]
    all_scores = [s for r in reports for s in r["scores"]]
    return {
        "dates": dates,
        "reports": reports,
        "n_episodes": len(all_scores),
        "avg": {
            k: (sum(s[k] for s in all_scores) / len(all_scores)) if all_scores else 0
            for k in ("accuracy", "coverage", "fluency")
        },
        "verdicts": Counter(s["verdict"] for s in all_scores),
    }


# ── Ask Gemini to cluster the findings into actionable patterns ───────────────
TRENDS_SYSTEM = (
    "You are an editor improving the PROMPT that drives an automatically "
    "generated Hebrew medical podcast. You are given QC findings collected over "
    "several weeks. Your job is to find the RECURRING problems — the ones that "
    "show up week after week — and propose a concrete change to the prompt for "
    "each. Ignore one-off issues. Reply with ONLY a JSON object."
)


def _instructions(min_count: int) -> str:
    return (
        "Return JSON: {\"patterns\": [ ... ]} where each pattern is\n"
        '  {"title": "<short Hebrew name for the recurring problem>",\n'
        '   "occurrences": <integer, how many separate findings support it>,\n'
        '   "evidence": [<up to 3 short Hebrew quotes from the findings>],\n'
        '   "diagnosis": "<one Hebrew sentence: why this keeps happening>",\n'
        '   "fixable_by_prompt": true|false,\n'
        '   "proposed_instruction": "<the EXACT sentence(s) to add to or change '
        'in the prompt — English is fine, this text goes into the prompt; empty '
        'if fixable_by_prompt is false>",\n'
        '   "note": "<if not fixable by prompt, one Hebrew sentence on what '
        'would actually help>"}\n'
        f"Only include patterns supported by at least {min_count} findings. "
        "Order by occurrences, highest first. Be honest when something is a "
        "hard limitation of the text-to-speech or of NotebookLM rather than "
        "something a prompt can fix — set fixable_by_prompt false and say so.\n"
        "Do NOT propose changes that fight the podcast's intended design: the "
        "AI disclaimer, saying the full journal name, stating the study type, "
        "the opening framing, clinical interpretation, and the two-host "
        "conversation are all deliberate."
    )


def analyse(data: dict, min_count: int, model: str) -> dict | None:
    key = (os.environ.get("GEMINI_API_KEY")
           or os.environ.get("GOOGLE_API_KEY") or "").strip()
    if not key:
        print("QC trends skipped: GEMINI_API_KEY not set.")
        return None
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        print("QC trends skipped: `google-genai` not installed.")
        return None

    lines = []
    for r in data["reports"]:
        if not (r["discrepancies"] or r["notes"]):
            continue
        lines.append(f"### {r['date']}")
        for d in r["discrepancies"]:
            lines.append(f"- [{d['severity']}] נאמר: {d['said']} | מקור: {d['source']}")
        for n in r["notes"]:
            lines.append(f"- הערה: {n}")
    findings = "\n".join(lines)
    if not findings.strip():
        print("No QC findings to analyse yet.")
        return None

    user = (
        f"{_instructions(min_count)}\n\n"
        f"=== QC FINDINGS ACROSS {len(data['dates'])} RUNS ===\n{findings[:60000]}"
    )
    try:
        client = genai.Client(api_key=key)
        resp = client.models.generate_content(
            model=model, contents=user,
            config=types.GenerateContentConfig(
                system_instruction=TRENDS_SYSTEM,
                response_mime_type="application/json",
                thinking_config=types.ThinkingConfig(thinking_budget=4096),
                max_output_tokens=12000, temperature=0.3,
            ),
        )
        text = (resp.text or "").strip()
        a, b = text.find("{"), text.rfind("}")
        return json.loads(text[a:b + 1]) if a >= 0 else None
    except Exception as e:
        print(f"  Trends analysis failed: {e}")
        return None


# ── Report ────────────────────────────────────────────────────────────────────
def write_report(data: dict, result: dict) -> Path:
    pats = result.get("patterns", []) if result else []
    v = data["verdicts"]
    lines = [
        "# 📈 מגמות בקרת איכות — דפוסים חוזרים והצעות לשיפור",
        "",
        f"*מבוסס על {len(data['dates'])} ריצות ({data['dates'][-1]} – "
        f"{data['dates'][0]}), {data['n_episodes']} פרקים.*",
        "",
        "## ציונים ממוצעים",
        "",
        "| מדד | ממוצע |",
        "|---|:---:|",
        f"| דיוק | {data['avg']['accuracy']:.2f} / 5 |",
        f"| כיסוי | {data['avg']['coverage']:.2f} / 5 |",
        f"| שטף | {data['avg']['fluency']:.2f} / 5 |",
        "",
        f"סיכומים: ✅ {v.get('ok', 0)} · 🟡 {v.get('review', 0)} · "
        f"🔴 {v.get('problem', 0)}",
        "",
        "---",
        "",
        "## דפוסים חוזרים",
        "",
    ]
    if not pats:
        lines.append("*לא זוהו דפוסים חוזרים בסף שנבחר — כנראה סימן טוב.*")
    for i, p in enumerate(pats, 1):
        fixable = p.get("fixable_by_prompt")
        badge = "🔧 ניתן לתקן בפרומפט" if fixable else "⛔ מגבלה — לא ניתן לתקן בפרומפט"
        lines += [
            f"### {i}. {p.get('title','')}  ({p.get('occurrences','?')} מופעים)",
            "",
            f"**{badge}**",
            "",
            f"*אבחנה:* {p.get('diagnosis','')}",
            "",
        ]
        ev = p.get("evidence") or []
        if ev:
            lines.append("*דוגמאות:*")
            lines += [f"- {e}" for e in ev]
            lines.append("")
        if fixable and p.get("proposed_instruction"):
            lines += [
                "*הצעת ניסוח להוספה לפרומפט:*",
                "",
                "```text",
                p["proposed_instruction"],
                "```",
                "",
            ]
        elif p.get("note"):
            lines += [f"*מה כן יעזור:* {p['note']}", ""]
    lines += [
        "---",
        "",
        "> הצעות בלבד — אף שינוי לא הוחל אוטומטית. NotebookLM אינו לומד בין "
        "פרקים והפלט אינו דטרמיניסטי, ולכן שינוי פרומפט נעשה רק באישור אנושי.",
    ]
    out = REPO_ROOT / "summaries" / "qc-trends.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Wrote {out.relative_to(REPO_ROOT)}")
    return out


def notify(data: dict, result: dict) -> None:
    topic = os.environ.get("NTFY_TOPIC", "").strip()
    if not topic:
        return
    pats = (result or {}).get("patterns", [])
    fixable = sum(1 for p in pats if p.get("fixable_by_prompt"))
    repo = os.environ.get("GH_REPO") or os.environ.get("GITHUB_REPOSITORY", "")
    payload = {
        "topic": topic,
        "title": "📈 מגמות בקרת איכות",
        "message": (f"{len(pats)} דפוסים חוזרים על פני {len(data['dates'])} ריצות · "
                    f"{fixable} ניתנים לתיקון בפרומפט · "
                    f"דיוק ממוצע {data['avg']['accuracy']:.1f}/5"),
        "priority": 3, "tags": ["chart_with_upwards_trend"],
    }
    if repo:
        url = f"https://github.com/{repo}/blob/main/summaries/qc-trends.md"
        payload["click"] = url
        payload["actions"] = [{"action": "view", "label": "📈 הדוח", "url": url}]
    try:
        requests.post("https://ntfy.sh", json=payload, timeout=15)
    except Exception as e:
        print(f"  ntfy failed: {e}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Recurring QC patterns -> prompt proposals.")
    ap.add_argument("--weeks", type=int, default=8, help="how many runs to read")
    ap.add_argument("--min-count", type=int, default=2,
                    help="minimum findings for a pattern to count")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    args = ap.parse_args()

    print(f"\n📈 QC trends over the last {args.weeks} run(s)...")
    data = harvest(args.weeks)
    if not data["dates"]:
        print("  No QC reports found yet."); return 0
    print(f"  {data['n_episodes']} episodes across {len(data['dates'])} runs; "
          f"avg accuracy {data['avg']['accuracy']:.2f}")
    result = analyse(data, args.min_count, args.model)
    if result is None:
        return 0
    write_report(data, result)
    notify(data, result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
